packages:
  - 'core'
  - 'cosyne'
  - 'designer'
  - 'examples'
  - 'phone-apps'
  - 'phone-apps/alarms'
  - 'phone-apps/battery'
  - 'phone-apps/burning-ship'
  - 'phone-apps/clock'
  - 'phone-apps/eliza'
  - 'phone-apps/eyes'
  - 'phone-apps/hexview'
  - 'phone-apps/julia-set'
  - 'phone-apps/mandelbrot'
  - 'phone-apps/minefield'
  - 'phone-apps/newton-fractal'
  - 'phone-apps/notes'
  - 'phone-apps/pixyne'
  - 'phone-apps/signal'
  - 'phone-apps/snowflake'
  - 'phone-apps/sonic3'
  - 'phone-apps/sshterm'
  - 'phone-apps/stopwatch'
  - 'phone-apps/telegram'
  - 'phone-apps/timer'
  - 'phone-apps/tricorn'
  - 'ported-apps/3d-cube'
  - 'ported-apps/calcudoku'
  - 'ported-apps/chess'
  - 'ported-apps/disk-tree'
  - 'ported-apps/edlin'
  - 'ported-apps/falling-blocks'
  - 'ported-apps/falling-letters'
  - 'ported-apps/find-pairs'
  - 'ported-apps/fps-advanced'
  - 'ported-apps/fyles'
  - 'ported-apps/game-of-life'
  - 'ported-apps/grand-perspective'
  - 'ported-apps/image-resizer'
  - 'ported-apps/image-viewer'
  - 'ported-apps/mahjongg'
  - 'ported-apps/nomad'
  - 'ported-apps/notes'
  - 'ported-apps/peg-solitaire'
  - 'ported-apps/pixeledit'
  - 'ported-apps/pomodoro'
  - 'ported-apps/prime-grid-visualizer'
  - 'ported-apps/script-schmiede-fractals'
  - 'ported-apps/slider-puzzle'
  - 'ported-apps/slydes'
  - 'ported-apps/sokol-arcade/fps-voxel'
  - 'ported-apps/solitaire'
  - 'ported-apps/spherical-snake'
  - 'ported-apps/spiral'
  - 'ported-apps/sudoku'
  - 'ported-apps/tango-puzzle'
  - 'ported-apps/terminal'
  - 'ported-apps/torus'
  - 'ported-apps/tsyet-another-doom-clone'
  - 'ported-apps/wave2'
  - 'ported-apps/zip-puzzle'
